### ISSUE TITLE
FROM not working with private registries or slashes

### ISSUE THREAD

**Issue by svogt** [domeide/doclipser#26]
FROM host:port/repo/image gives error: mismatched input '<port>' expecting RULE_ID

If the host has a dash, it fails with: missing EOF at '-'

If you just have "FROM repo/image" it fails with: missing EOF at '/'

**Comment by thomasdarimont** [comment]
I have the same problem - with doclipser in STS 3.7.1 (SpringSource Tool Suite)

**Comment by l0rd** [comment]
Thanks for your feedback @svogt and @thomasdarimont. I didn't had the chance to work on it in the last months but I should fix that in the next weeks.
